openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0
paths:
  /api/users:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ApiUser'
                type: array
          description: OK
      summary: List all users
      tags:
      - users
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiUser'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
          description: Created
      summary: Create a user
      tags:
      - users
  /api/users/{id}:
    delete:
      operationId: deleteUserById
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
          description: OK
      security:
      - bearerAuth: []
      summary: Delete user by ID
      tags:
      - users
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
          description: OK
      summary: Get user by ID
      tags:
      - users
    patch:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiUser'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
          description: OK
      summary: Update user
      tags:
      - users
components:
  schemas:
    ApiUser:
      properties:
        email:
          type: string
        id:
          type: string
        name:
          type: string
      type: object
  securitySchemes:
    apiKey:
      in: header
      name: X-API-Key
      type: apiKey
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
