openapi: 3.1.2
info:
  title: Users API
  version: 1.0.0
paths:
  /api/users:
    get:
      tags:
        - users
      summary: List all users
      description: List all users
      responses:
        '200':
          description: list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiUser'
    post:
      tags:
        - users
      summary: Create a user
      description: Create a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiUser'
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
        '400':
          description: bad request
  /api/users/{id}:
    get:
      tags:
        - users
      summary: Get user by ID
      description: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: user found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
        '404':
          description: user not found
    delete:
      tags:
        - users
      summary: Delete user by ID
      description: Delete user by ID
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: user deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiUser'
      security:
        - bearerAuth: []
components:
  schemas:
    ApiUser:
      type: object
      properties:
        email:
          type: string
        id:
          type: string
        name:
          type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
