openapi: 3.0.3
info:
  title: Reviews API (Fiber)
  version: 1.0.0
paths:
  /reviews:
    get:
      tags:
        - reviews
      summary: List all reviews
      description: List all reviews
      responses:
        "200":
          description: list of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiReview"
      security:
        - bearerAuth: []
    post:
      tags:
        - reviews
      summary: Create a review
      description: Create a review
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiCreateReviewRequest"
      responses:
        "201":
          description: review created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiReview"
        "400":
          description: invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - bearerAuth: []
  /reviews/{id}:
    get:
      tags:
        - reviews
      summary: Get review by ID
      description: Get review by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: review found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiReview"
        "404":
          description: review not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      security:
        - bearerAuth: []
components:
  schemas:
    ApiCreateReviewRequest:
      type: object
      properties:
        author:
          type: string
        comment:
          type: string
        rating:
          type: integer
          format: int32
    ApiReview:
      type: object
      properties:
        author:
          type: string
        comment:
          type: string
        id:
          type: integer
          format: int32
        rating:
          type: integer
          format: int32
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
