openapi: 3.0.3
info:
  title: Products API (Echo)
  version: 1.0.0
paths:
  /products:
    get:
      tags:
        - products
      summary: List all products
      description: List all products
      parameters:
        - name: category
          in: query
          schema:
            type: string
        - name: max_price
          in: query
          schema:
            type: number
            format: double
      responses:
        "200":
          description: list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiProduct"
    post:
      tags:
        - products
      summary: Create a product
      description: Create a product
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiCreateProductRequest"
      responses:
        "201":
          description: product created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiProduct"
        "400":
          description: invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /products/{id}:
    get:
      tags:
        - products
      summary: Get product by ID
      description: Get product by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiProduct"
components:
  schemas:
    ApiCreateProductRequest:
      type: object
      properties:
        category:
          type: string
        price:
          type: number
          format: double
        title:
          type: string
    ApiProduct:
      type: object
      properties:
        category:
          type: string
        id:
          type: integer
          format: int32
        price:
          type: number
          format: double
        title:
          type: string
