openapi: 3.0.3
info:
  title: Todo API
  version: 1.0.0
paths:
  /todos:
    get:
      responses:
        "200":
          content:
            application/json:
              example:
                data: []
                message: ok
              schema:
                $ref: '#/components/schemas/ModelResponseTodoList'
          description: OK
        "401":
          content:
            application/json:
              example:
                error: unauthorized
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Unauthorized
      security:
      - apiKey: []
      summary: List all todos
      tags:
      - todos
    post:
      requestBody:
        content:
          application/json:
            example:
              description: Milk, eggs, bread
              title: Buy groceries
            schema:
              $ref: '#/components/schemas/ModelCreateTodoRequest'
      responses:
        "201":
          content:
            application/json:
              example:
                data:
                  created_at: "2026-04-10T02:05:15.278387Z"
                  description: Milk, eggs, bread
                  done: false
                  id: 1
                  title: Buy groceries
                  updated_at: "2026-04-10T02:05:15.278387Z"
                message: created
              schema:
                $ref: '#/components/schemas/ModelResponseTodo'
          description: Created
        "400":
          content:
            application/json:
              example:
                error: invalid character 'o' in literal null (expecting 'u')
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              example:
                error: unauthorized
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Unauthorized
      security:
      - apiKey: []
      summary: Create a todo
      tags:
      - todos
  /todos/{id}:
    delete:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              example:
                error: unauthorized
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Unauthorized
        "404":
          content:
            application/json:
              example:
                error: todo not found
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Not Found
      security:
      - apiKey: []
      summary: Delete a todo
      tags:
      - todos
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              example:
                data:
                  created_at: "2026-04-10T02:05:15.28183Z"
                  description: Milk and eggs
                  done: false
                  id: 1
                  title: Buy groceries
                  updated_at: "2026-04-10T02:05:15.28183Z"
                message: ok
              schema:
                $ref: '#/components/schemas/ModelResponseTodo'
          description: OK
        "401":
          content:
            application/json:
              example:
                error: unauthorized
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Unauthorized
        "404":
          content:
            application/json:
              example:
                error: todo not found
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Not Found
      security:
      - apiKey: []
      summary: Get a todo by ID
      tags:
      - todos
    put:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            example:
              description: Cover all endpoints and edge cases
              done: false
              title: Write tests (revised)
            schema:
              $ref: '#/components/schemas/ModelUpdateTodoRequest'
      responses:
        "200":
          content:
            application/json:
              example:
                data:
                  created_at: "2026-04-10T02:05:15.283853Z"
                  description: Cover all endpoints and edge cases
                  done: false
                  id: 1
                  title: Write tests (revised)
                  updated_at: "2026-04-10T02:05:15.284155Z"
                message: ok
              schema:
                $ref: '#/components/schemas/ModelResponseTodo'
          description: OK
        "400":
          content:
            application/json:
              example:
                error: invalid character 'o' in literal null (expecting 'u')
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Bad Request
        "401":
          content:
            application/json:
              example:
                error: unauthorized
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Unauthorized
        "404":
          content:
            application/json:
              example:
                error: todo not found
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Not Found
      security:
      - apiKey: []
      summary: Update a todo
      tags:
      - todos
  /todos/{id}/done:
    patch:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              example:
                data:
                  created_at: "2026-04-10T02:05:15.286037Z"
                  description: Push to production
                  done: true
                  id: 1
                  title: Deploy service
                  updated_at: "2026-04-10T02:05:15.28634Z"
                message: ok
              schema:
                $ref: '#/components/schemas/ModelResponseTodo'
          description: OK
        "401":
          content:
            application/json:
              example:
                error: unauthorized
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Unauthorized
        "404":
          content:
            application/json:
              example:
                error: todo not found
              schema:
                properties:
                  error:
                    type: string
                type: object
          description: Not Found
      security:
      - apiKey: []
      summary: Mark a todo as done
      tags:
      - todos
components:
  schemas:
    ModelCreateTodoRequest:
      properties:
        description:
          type: string
        title:
          type: string
      type: object
    ModelResponseTodo:
      properties:
        data:
          $ref: '#/components/schemas/ModelTodo'
        message:
          type: string
      type: object
    ModelResponseTodoList:
      properties:
        data:
          items:
            $ref: '#/components/schemas/ModelTodo'
          nullable: true
          type: array
        message:
          type: string
      type: object
    ModelTodo:
      properties:
        created_at:
          format: date-time
          type: string
        description:
          type: string
        done:
          type: boolean
        id:
          format: int64
          type: integer
        title:
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
    ModelUpdateTodoRequest:
      properties:
        description:
          type: string
        done:
          type: boolean
        title:
          type: string
      type: object
  securitySchemes:
    apiKey:
      in: header
      name: X-API-Key
      type: apiKey
