openapi: 3.0.3
info:
  title: Tasks API (Gorilla)
  version: 1.0.0
paths:
  /tasks:
    get:
      tags:
        - tasks
      summary: List all tasks
      description: List all tasks
      responses:
        "200":
          description: list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiTask"
    post:
      tags:
        - tasks
      summary: Create a task
      description: Create a task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiCreateTaskRequest"
      responses:
        "201":
          description: task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiTask"
        "400":
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /tasks/{id}:
    get:
      tags:
        - tasks
      summary: Get task by ID
      description: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiTask"
        "404":
          description: task not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      tags:
        - tasks
      summary: Delete a task
      description: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: task deleted
components:
  schemas:
    ApiCreateTaskRequest:
      type: object
      properties:
        title:
          type: string
    ApiTask:
      type: object
      properties:
        done:
          type: boolean
        id:
          type: integer
          format: int32
        title:
          type: string
